#!/usr/bin/env zsh

set -e

taps=(
  caskroom/cask
  caskroom/fonts
)

packages=(
  openssl
  libyaml
  automake

  # All the other "standard" packages
  coreutils
  dnsmasq
  dnstop
  gist
  "git --with-pcre --with-brewed-curl --with-blk-sha1 --with-gettext --with-brewed-openssl --with-persistent-https"
  git-extras
  gnu-sed
  gnu-time
  gnutls
  hub
  lynx
  netcat
  ngrep
  pkg-config
  "python --with-brewed-openssl"
  "python3 --with-brewed-openssl"
  tomcat
  tree
  unrar
  watch
  wget

  # caskroom/cask
  brew-cask
)

cask_packages=(
  # java

  # Quick look plugins
  # epubquicklook
  # qlcolorcode
  # qlmarkdown
  # qlprettypatch
  # qlstephen
  # quicklook-csv
  # quicklook-json
  # scriptql
  # suspicious-package
  # webpquicklook

  # # Other apps
  # bonjour-browser
  # charles
  # evernote
  # firefox
  # gitx
  # httpscoop
  # skype
  # spotify
  # vagrant
  virtualbox

  # caskroom/fonts
  font-inconsolata
  font-liberation-sans
  font-open-sans
  font-source-code-pro
  font-source-sans-pro
)

function log() {
  echo $* > /dev/stderr
}

#########################################################################

log "brew update"
brew update

log "brew upgrade"
brew upgrade

log "Tapping.."
for name in $taps
do
  log "brew tap ${name}"
  brew tap $name
done

log "Installing"
for name_and_args in $packages
do
  log "brew install ${=name_and_args}"
  brew install "${=name_and_args}"
done

for name_and_args in $cask_packages
do
  log "brew cask install ${=name_and_args}"
  brew cask install "${=name_and_args}"
done

log "brew cleanup"
brew cleanup

